#!/bin/sh

_scripts="$HOME/bin"

die() {
	[ ! -z "$@" ] && echo "$@"
	exit 1
}

new_script() {
	[ -z "$1" ] && die "You must provide script name!"
	file="${_scripts:-$HOME/bin}/$1"

	touch "$file" || die "Couldn't create $file"
	echo '#!/bin/sh' > "$file"
	echo >> "$file"
	chmod +x "$file"
}

while [ "$#" -gt 0 ]
do

	case "$1" in
		script) new_script "$2"; shift 2 ;;
		*) die "Unknown command $1" ;;
	esac

	exit 0

done
