#!/bin/sh

die() {
	[ ! -z "$@" ] && echo "$@"
	exit 1
}

sha1="$(selsave -l | ursa -s 40 -p up -n fzfu -c 'fzf --preview-window=right:74% --preview="cat /tmp/selsave/{}"')"

if [ -z "$sha1" ]; then
	die "You have not selected any hash!"
else
	xsel --clipboard < "/tmp/selsave/$sha1" 
fi
