#!/bin/sh

usage() {
	cat <<EOF
selsave [--list]

If no argument, try to save current CLIPBOARD selectoin into file.

Options:
	--list | -l
	List all saved clipboards in mdate order

	--clear | -c
	Clear all saved clipboards
EOF
}

tmpdir="/tmp/selsave"
if [ ! -d "$tmpdir" ]; then
	mkdir -p "$tmpdir"
fi

while [ "$#" -gt 0 ]
do

	case "$1" in
		--help|-h) usage; exit 0;;
		--list|-l) ls --sort=time "$tmpdir"; exit 0;;
		--clear|-c) { cd "${tmpdir:-/tmp/selsave}" && rm ./*; exit 0; }
	esac

done

clipboard="$(xsel --clipboard)"
[ -z "$clipboard" ] && exit 0

sha1="$(echo "$clipboard" | sha1sum | cut -d" " -f1)"
file="${tmpdir}/${sha1}"

if [ -f "$file" ]; then
	touch "$file"
else
	echo "$clipboard" > "$file"
fi

# point to current sha1 file
#ln --symbolic --force "$file" "${tmpdir}/latest"

# clipboard have to be restored, otherwise it stays empty (idk why)
echo "$clipboard" | xsel -b -i
