#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

config="$HOME/.gitconfig.local"

[ -e "$config" ] || touch "$config"

read -rp "Enter Git username: [Paweł Smolak] " username
read -rp "Enter Git email: [smolak.paul@gmail.com] " email

cat << EOF >> .gitconfig
[user]
    name = ${username:="Paweł Smolak"}
    email = ${email:="smolak.paul@gmail.com"}
EOF

cat << EOF >> "$config"
[includeIf "gitdir:$(pwd)/"]
    path = $(pwd)/.gitconfig
EOF

echo "Local git configuration set for $(pwd)."
